### ISSUE TITLE
怎么看不见中文文档呢?

### ISSUE THREAD

**Issue by airenqingqing** [scrypt-sv/specification#4]
怎么看不见中文文档呢?

**Comment by baryon** [comment]
https://wiki.bsv.info


2020年9月13日(日) 1:00 airenqingqing <notifications@github.com>:

**Comment by xhliu** [comment]
Coming soon

**Comment by xhliu** [comment]
来了https://scryptdoc.readthedocs.io/zh_CN/latest/ @airenqingqing
